SecureApiGateway/secure-api-gateway-ob-uk-common

- securebanking-openbanking-uk-bom/pom.xml
- securebanking-openbanking-uk-common/pom.xml
- securebanking-openbanking-uk-common/src/main/java/com/forgerock/securebanking/openbanking/uk/common/api/meta/OBVersion.java
- securebanking-openbanking-uk-error/pom.xml
- securebanking-openbanking-uk-forgerock-datamodel/pom.xml
- securebanking-openbanking-uk-forgerock-datamodel/src/main/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/payment/FRFundsConfirmationResponse.java
- securebanking-openbanking-uk-forgerock-datamodel/src/test/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/testsupport/FRAccountIdentifierTestDataFactory.java
- securebanking-openbanking-uk-forgerock-datamodel/src/test/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/testsupport/FRAmountTestDataFactory.java
- securebanking-openbanking-uk-forgerock-datamodel/src/test/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/testsupport/FRCashBalanceTestDataFactory.java
- securebanking-openbanking-uk-forgerock-datamodel/src/test/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/testsupport/FRFinancialAccountTestDataFactory.java
- Added FRFundsConfirmationResponse for bank simulator's backoffice API
- Added test data factories for FR data objects
- Added OBVersion
- Added licence check plugin to missing modules
Issue: https://github.com/SecureBankingAcceleratorToolkit/SecureBankingAcceleratorToolkit/issues/33
> 33 - FRFundsConfirmationResponse and test data factories

- securebanking-openbanking-uk-forgerock-datamodel/src/test/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/testsupport/FRFinancialAgentTestDataFactory.java
- securebanking-openbanking-uk-forgerock-datamodel/src/test/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/testsupport/FRPostalAddressTestDataFactory.java
- securebanking-openbanking-uk-forgerock-datamodel/src/test/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/testsupport/account/FRAccountBeneficiaryTestDataFactory.java
- securebanking-openbanking-uk-forgerock-datamodel/src/test/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/testsupport/account/FRCashBalanceTestDataFactory.java
- securebanking-openbanking-uk-forgerock-datamodel/src/test/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/testsupport/account/FRDirectDebitDataTestDataFactory.java
- securebanking-openbanking-uk-forgerock-datamodel/src/test/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/testsupport/account/FRFinancialAccountTestDataFactory.java
- securebanking-openbanking-uk-forgerock-datamodel/src/test/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/testsupport/account/FROfferDataTestDataFactory.java
- securebanking-openbanking-uk-forgerock-datamodel/src/test/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/testsupport/account/FRPartyDataTestDataFactory.java
- securebanking-openbanking-uk-forgerock-datamodel/src/test/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/testsupport/account/FRScheduledPaymentDataTestDataFactory.java
- securebanking-openbanking-uk-forgerock-datamodel/src/test/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/testsupport/account/FRStandingOrderDataTestDataFactory.java
- securebanking-openbanking-uk-forgerock-datamodel/src/test/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/testsupport/account/FRStatementDataTestDataFactory.java
- securebanking-openbanking-uk-forgerock-datamodel/src/test/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/testsupport/account/FRTransactionDataTestDataFactory.java
These are for use in the simulator and the functional tests. They can also be used by customers if required.
Issue: https://github.com/SecureBankingAcceleratorToolkit/SecureBankingAcceleratorToolkit/issues/46
> 46 Test data factories

- securebanking-openbanking-uk-forgerock-datamodel/src/main/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/account/FRBalanceType.java
- securebanking-openbanking-uk-forgerock-datamodel/src/main/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/account/FRCreditDebitIndicator.java
- securebanking-openbanking-uk-forgerock-datamodel/src/main/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/account/FRCreditLine.java
- securebanking-openbanking-uk-forgerock-datamodel/src/main/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/account/FRFinancialAccount.java
- securebanking-openbanking-uk-forgerock-datamodel/src/main/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/payment/FRAccountIdentifier.java
Rather than using the unconventional format that the OB objects use (e.g. `AccountId` rather than `accountId`), this PR switches back to the standard `accountId` type format. Some minor modifications have been made to the securebanking RCS UI to accommodate this format.
Additionally, some `@JsonCreator` and `@JsonValue` properties were missing on some of the enuns.
Issue: https://github.com/SecureBankingAcceleratorToolkit/SecureBankingAcceleratorToolkit/issues/62
> 62 JSON fixes for the RCS UI

- securebanking-openbanking-uk-obie-datamodel/src/test/java/uk/org/openbanking/testsupport/payment/OBWriteFileConsentTestDataFactory.java
Separated out factory method for `OBWriteFile2DataInitiation` so it can be called elsewhere.
Issue: https://github.com/OpenBankingToolkit/openbanking-toolkit/issues/27
> 27 - Separated out factory method for OBWriteFile2DataInitiation

- securebanking-openbanking-uk-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/account/OBBeneficiary5Basic.java
- securebanking-openbanking-uk-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/account/OBBeneficiary5Detail.java
- securebanking-openbanking-uk-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/account/OBReadProduct2DataOtherProductType.java
- securebanking-openbanking-uk-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/account/OBStandingOrder6Basic.java
- securebanking-openbanking-uk-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/account/OBStandingOrder6Detail.java
- securebanking-openbanking-uk-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/account/OBTransaction6Basic.java
- securebanking-openbanking-uk-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/account/OBTransaction6Detail.java
The benefit of overwriting existing classes is that you're less likely to miss changes to them, but it's not without risk. It looks like I shouldn't have changed `OBSupplementaryData1` to a `Map` (since we deliberately have `OBSupplementaryData1Serializer` and `OBSupplementaryData1Deserializer` for this).
**Issue**: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/76
> 76 - v3.1.8 Accounts API OBSupplementaryData1 rollback

- securebanking-openbanking-uk-forgerock-datamodel/src/main/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/account/FRFinancialAccount.java
- securebanking-openbanking-uk-forgerock-datamodel/src/main/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/common/FRAccountIdentifier.java
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/297
- Add accountId field in FRAccountIdentifier class
- Create a method to get the first account from the list of FRAccountIdentifier in the FRFinancialAccount class
> Add accountId in FRAccountIdentifier

- securebanking-openbanking-uk-obie-datamodel/src/test/java/uk/org/openbanking/testsupport/payment/OBAmountTestDataFactory.java
- securebanking-openbanking-uk-obie-datamodel/src/test/java/uk/org/openbanking/testsupport/payment/OBWriteDomesticStandingOrderConsentTestDataFactory.java
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/350
> 350: Create methods to initialize OBWriteDomesticStandingOrderConsent2, OBWriteDomesticStandingOrderConsent3 objects in TestDataFactory

- securebanking-openbanking-uk-obie-datamodel/src/test/java/uk/org/openbanking/testsupport/payment/OBAccountTestDataFactory.java
- securebanking-openbanking-uk-obie-datamodel/src/test/java/uk/org/openbanking/testsupport/payment/OBWriteInternationalConsentTestDataFactory.java
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/374
> 374: Create methods with only mandatory fields for International payment consent

- securebanking-openbanking-uk-obie-datamodel/src/test/java/uk/org/openbanking/testsupport/payment/OBWriteInternationalScheduledConsentTestDataFactory.java
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/413
> 413: Create methods with only mandatory fields for international scheduled consent

- securebanking-openbanking-uk-obie-datamodel/pom.xml
Currently, the codegen produces output which includes an unused import for JsonNullable. This causes issues as this class is not on the classpath and therefore causes compilation errors. Disabling support for JsonNullable as we don't use this functionality and it seems unlikely that we would want to in the future.
More information on JsonNullable can be found here: https://github.com/OpenAPITools/jackson-databind-nullable
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/446
> 450: Preventing the codegen from using JsonNullable

- securebanking-openbanking-uk-forgerock-datamodel/src/test/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/converter/common/FRLinksConverterTest.java
Adding unit tests for FRLinksConverter class.
This change was missed from the previous PR: https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk/pull/49
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/448
> 448: Adding FRLinksConverterTest

- securebanking-openbanking-uk-common/src/main/java/com/forgerock/securebanking/openbanking/uk/common/api/meta/obie/OBVersion.java
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/440
> 440: Adding v3_1_9 to OBVersion enum

- securebanking-openbanking-uk-common/src/main/java/com/forgerock/securebanking/openbanking/uk/common/api/meta/obie/OBVersion.java
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/424
> 424: Adding v3_1_10 to OBVersion enum

- securebanking-openbanking-uk-obie-datamodel/src/test/java/uk/org/openbanking/testsupport/payment/OBWriteInternationalStandingOrderConsentTestDataFactory.java
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/472
Description: Added methods with only mandatory fields for international standing order consents.
> 472: Create methods with only mandatory fields for international standing order consents

- securebanking-openbanking-uk-obie-datamodel/src/test/java/uk/org/openbanking/testsupport/payment/OBWriteFileConsentTestDataFactory.java
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/559
Description: Added methods with only mandatory fields for file payment consents.
> 559: Create methods to return file payment consents with only mandatory fields

- .gitignore
- securebanking-openbanking-uk-obie-datamodel/src/test/java/uk/org/openbanking/testsupport/payment/OBWriteFileConsentTestDataFactory.java
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/659
The OBWriteFileConsentTestDataFactory contaied hardcoded values for the following information that should have been calculated at functional tests runtime:
fileType
fileHash
numberOfTransactions
controlSum
Added the required changes to have the dynamic data passed to the functions.
> Adding parameterization to mandatory hardcoded values.

- securebanking-openbanking-uk-obie-datamodel/src/test/java/uk/org/openbanking/testsupport/vrp/OBDomesticVrpCommonTestDataFactory.java
- securebanking-openbanking-uk-obie-datamodel/src/test/java/uk/org/openbanking/testsupport/vrp/OBDomesticVrpConsentRequestTestDataFactory.java
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/645
Added methods that contain only the mandatory fields for the VRP consent request. These methods will be used in the functional tests.
> Adding methods with only mandatory fields

- securebanking-openbanking-uk-forgerock-datamodel/src/main/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/account/FRFinancialAccount.java
- First account not needs to be serialised
Issue: https://github.com/secureapigateway/secureapigateway/issues/637
> 637: vrp payment decision

- securebanking-openbanking-uk-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/payment/OBSCASupportData1.java
Issue: https://github.com/secureapigateway/secureapigateway/issues/586
Description: Fixed invalid max length definition.
> 586: Fixing OBIE data model bug in OBSCASupportData1 invalid max length definition

- .github/workflows/merge-master.yml
- .github/workflows/pr.yml
- .github/workflows/release.yml
- pom.xml
- secure-api-gateway-ob-uk-common-bom/pom.xml
This changes provide a way to create a release of the artifacts created in this repository
The release action call the reusable action `prepare release` that lives in a parent repository
- The prepare release workflow will create a tag from `master` and a branch with the release versions: 
- Creates a tag with master current version and the short has commit (to permits run the action multiple times without failures) 
- Updates the parent version from snapshot to the latest release 
- Remove the snapshot version from modules - 
- Creates a release branch
When finish the reusable workflow `release prepare` the `release` workflow will do:
- Build and publish the artifacts (release version or release candidates)
- Create a release draft in github
- Update the branch with the next snapshot …
> 812: release action

- pom.xml
Avoid release candidates versions
- Bumped gateway-parent version release 0.9.0
Issue: https://github.com/secureapigateway/secureapigateway/issues/812
> 812: release action prepare

- secure-api-gateway-ob-uk-common-error/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/error/OBRIErrorType.java
Issue: https://github.com/secureapigateway/secureapigateway/issues/575 
Description: Changed the `HttpStatus` for both `Initiation` & `Risk` validations from `"FORBIDDEN"` to `"BAD_REQUEST"` according to the spec. 
* E.g.: "The PISP must ensure that the `Initiation` and `Risk ` sections of the international-payment match the corresponding `Initiation` and `Risk` sections of the international-payment-consent resource. If the two do not match, the ASPSP must not process the request and must respond with a `400 (Bad Request)`." 
https://openbankinguk.github.io/read-write-api-site3/v3.1.4/resources-and-data-models/pisp/international-payments.html#post-international-payments 
* These requirements apply to all Payment APIs except for File Payments which does not contain both `Initiation` & …
> 575: Changing HttpStatus for the Initiation & Risk validations

- pom.xml
Use 0.9.1 parent pom
Issue: https://github.com/secureapigateway/secureapigateway/issues/932
> 932: Prepare for 0.9.1 release

- pom.xml
Use v1.0.0 of parent
Issue: https://github.com/secureapigateway/secureapigateway/issues/927
> 927: Update versions ready for v1.0.0 release

- secure-api-gateway-ob-uk-common-obie-datamodel/README.md
Added how to steps to update managed objects when new OB spec API version classes are generated.
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/948
> 948: update readme file to add steps to update the managed objects when a new OB spec API version classes is generated

- secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/jackson/DateTimeDeserializer.java
- secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/jackson/DateTimeSerializer.java
To compare datetimes between different objects using the equals method the date time must have the same chronology, instant and Time zone
- Modified date times deserializer and serializer to use UTC time zone offset and ISO date time, joda date time parser not needs an ISO date formatter because is supported by default.
Issue: https://github.com/secureapigateway/secureapigateway/issues/947
> 947: validate initiation object date times

- secure-api-gateway-ob-uk-common-error/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/error/OBRIErrorType.java
New error type for when a domestic VRP payment amount currency does not match the currency of the control parameters.
Fixing type in REQUEST_VRP_CONTROL_PARAMETERS_RULES error message.
This is required to build this PR in RS: https://github.com/SecureApiGateway/secure-api-gateway-ob-uk-rs/pull/175
https://github.com/SecureApiGateway/SecureApiGateway/issues/983
> 983: Adding OBRIErrorType.REQUEST_VRP_CONTROL_PARAMETER_CURRENCY_MISMATCH

- secure-api-gateway-ob-uk-common-obie-datamodel/src/test/java/uk/org/openbanking/testsupport/payment/OBExchangeRateTestDataFactory.java
- secure-api-gateway-ob-uk-common-obie-datamodel/src/test/java/uk/org/openbanking/testsupport/payment/OBWriteFileConsentTestDataFactory.java
~The components that deserialize/serialize and stores the consent as json object uses a mapper where the BigDecimals value differs from the request when a request is send to the RS backend.~ 
~The initiation equality verification fails because the bigDecimals between the initiation objects differs from submit payment request and consent retrieved from IDM where is stored in different precision format.~
~To cope that issue is provided a custom deserialization and serialization for the backend services to deserialize the BigDecimals object from the json payload always in the same way.~
~So that the equality verification of the initiation sections between payment submission and consent it's performed using the same BigDecimal precision format, either the request payload or the payload …
> 981 build BigDecimals with scale and rounding mode for dataFactories 

- secure-api-gateway-ob-uk-common-error/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/error/OBRIErrorType.java
The message previously mentioned Confirmation i.e. Funds Confirmation. Making the error message more generic so that it can be applied to any scenario that requires a consent with status Authorised.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1012
> 1012: Fixing OBRIErrorType.CONSENT_STATUS_NOT_AUTHORISED msg to be generic

- secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/common/FRCharge.java
- secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/common/FRChargeConverter.java
- secure-api-gateway-ob-uk-common-datamodel/src/test/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/common/FRChargeConverterTest.java
FRCharge is used to represent OBIE charges in payments APIs, such as type: OBWriteDomesticConsentResponse5DataCharges
Creating FRCharge so that we can represent charges in the Consent Store.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1023
> 1023: Adding FRCharge to datamodel

- secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/mapper/FRModelMapper.java
- secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/payment/FRWriteDomesticConsentConverter.java
- secure-api-gateway-ob-uk-common-datamodel/src/test/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/payment/FRWriteDomesticConsentConverterTest.java
Using the model mapper library to achieve this, as it cuts down the boilerplate code. Adding a custom type mapping definition to fix the issue with the typo in the OBRisk1.contractPresentInidicator property
https://github.com/SecureApiGateway/SecureApiGateway/issues/1023
> 1023: Adding a method to FRWriteDomesticConsentConverter to convert the FR type back to the OB type

- secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/vrp/FRDomesticVRPConsentConverters.java
- secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/vrp/FRDomesticVRPConsent.java
- secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/vrp/FRDomesticVRPConsentData.java
- secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/vrp/FRDomesticVRPControlParameters.java
- secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/vrp/FRPeriodicLimits.java
- secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/vrp/FRVRPInteractionType.java
- secure-api-gateway-ob-uk-common-datamodel/src/test/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/vrp/FRDomesticVRPConsentConvertersTest.java
- secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/vrp/OBDomesticVRPControlParameters.java
- secure-api-gateway-ob-uk-common-obie-datamodel/src/test/java/uk/org/openbanking/datamodel/vrp/OBDomesticVRPControlParametersTest.java
FR data model classes for VRP consents are required in order to store them in the RCS Consent Store.
Adding FRDomesticVRPConsentConverters to handle conversion between FR and OB types.
Fixing OBDomesticVRPControlParameters generated code to use the OBSupplementaryData1 type for the supplementaryData field. This is for consistency with other payments which reuse this common type.
Adding OBDomesticVRPControlParametersTest to catch if the above change is clobbered by re-generating the code.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1032
> 1032: Adding FR data model classes for VRP consents

- secure-api-gateway-ob-uk-common-error/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/error/OBRIErrorType.java
The extra information is leaking the accountIds that have been consented to in the error msg.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1035
> 1035: Removing extra information from UNAUTHORISED_ACCOUNT err msg

- secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/funds/FRFundsConfirmationConsentConverter.java
- secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/funds/FRFundsConfirmationConverter.java
- secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/mapper/FRModelMapper.java
- secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/funds/FRFundsConfirmationConsent.java
- secure-api-gateway-ob-uk-common-datamodel/src/test/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/funds/FRFundsConfirmationConsentConverterTest.java
- Created `FRFundsConfirmationConsent` object to wrap the `FRFundsConfirmationConsentData`
- Fix typo in `FRModelMapper`
- Upgrade `FRFundsConfirmationConsentConverter`
- Fix funds package
- Added test coverage for funds confirmation converter
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1084
> 1084: funds confirmation consent

- secure-api-gateway-ob-uk-common-error/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/error/OBRIErrorType.java
https://github.com/SecureApiGateway/SecureApiGateway/issues/958
> 958: Making IDEMPOTENCY_KEY_REQUEST_BODY_CHANGED error more concise

- secure-api-gateway-ob-uk-common-shared/src/main/java/com/forgerock/sapi/gateway/uk/common/shared/spring/converter/DateToUTCDateTimeConverter.java
- secure-api-gateway-ob-uk-common-shared/src/test/java/com/forgerock/sapi/gateway/uk/common/shared/spring/converter/DateToUTCDateTimeConverterTest.java
Converter which converts a java.util.Date to org.joda.time.DateTime, specifying the timezone as UTC.
This can be used to decode Date objects from Mongo as UTC.
Adding this to common so that we can use this converter in the RS and RCS.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1090
> 1090: Adding DateToUTCDateTimeConverter spring converter

- pom.xml
- secure-api-gateway-ob-uk-common-bom/pom.xml
- secure-api-gateway-ob-uk-common-datamodel/pom.xml
- secure-api-gateway-ob-uk-common-error/pom.xml
- secure-api-gateway-ob-uk-common-error/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/error/ErrorCode.java
- secure-api-gateway-ob-uk-common-error/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/error/OBRIErrorType.java
- secure-api-gateway-ob-uk-common-obie-datamodel/pom.xml
- secure-api-gateway-ob-uk-common-shared/pom.xml
- Replacing REQUEST_FILE_XML_INVALID/REQUEST_FILE_JSON_INVALID OBRIErrorTypes with generic: REQUEST_FILE_INVALID
- Adding REQUEST_FILE_TYPE_NOT_SUPPORTED OBRIErrorType
- Bumping version to 1.0.7-SNAPSHOT to avoid breaking compilation of RS master branch
- Required to build: https://github.com/SecureApiGateway/secure-api-gateway-ob-uk-rs/pull/227
https://github.com/SecureApiGateway/SecureApiGateway/issues/1095
> 1095: Error codes for File Payments

- secure-api-gateway-ob-uk-common-error/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/error/OBRIErrorType.java
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1124
Description: 
- Added missing Enum values for BT/MT `INVALID_LOCAL_INSTRUMENT`
- Fixed typos
> 1124: Adding missing BalanceTransfer/MoneyTransfer invalid LocalInstrument values to OBRIErrorType Enum

- secure-api-gateway-ob-uk-common-error/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/error/OBRIErrorType.java
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1142 
Description:
- Added generic failure error case for domestic vrp `ControlParameters` to ` OBRIErrorType` enum 
- Fixed typos
> 1142: Adding generic failure error case for domestic vrp ControlParameters

- secure-api-gateway-ob-uk-common-shared/pom.xml
- secure-api-gateway-ob-uk-common-shared/src/main/java/com/forgerock/sapi/gateway/uk/common/shared/spring/web/filter/FapiInteractionIdFilter.java
- secure-api-gateway-ob-uk-common-shared/src/test/java/com/forgerock/sapi/gateway/uk/common/shared/spring/web/filter/FapiInteractionIdFilterTest.java
Spring applications can install the FapInteractionIdFilter and be able to trace requests through the system using the x-fapi-interaction-id (if they log the MDC values with each log message).
https://github.com/SecureApiGateway/SecureApiGateway/issues/863
> 863: Adding FapiInteractionIdFilter which stores the x-fapi-interaction-id header value in the logging context (MDC)

- secure-api-gateway-ob-uk-common-shared/src/main/java/com/forgerock/sapi/gateway/uk/common/shared/fapi/FapiInteractionIdContext.java
- secure-api-gateway-ob-uk-common-shared/src/main/java/com/forgerock/sapi/gateway/uk/common/shared/spring/web/filter/FapiInteractionIdFilter.java
- secure-api-gateway-ob-uk-common-shared/src/test/java/com/forgerock/sapi/gateway/uk/common/shared/fapi/FapiInteractionIdContextTest.java
- secure-api-gateway-ob-uk-common-shared/src/test/java/com/forgerock/sapi/gateway/uk/common/shared/spring/web/filter/FapiInteractionIdFilterTest.java
FapiInteractionIdContext allows the x-fapi-interaction-id to be propagated to HTTP requests being made by the system, so that the same id can be used to trace the request across multiple systems.
Updating FapiInteractionIdFilter to manage the id in the context (as well as in MDC).
This PR: https://github.com/SecureApiGateway/secure-api-gateway-ob-uk-rcs/pull/187 demonstrates how the context can be used to set the x-fapi-interaction-id in HTTP Requests.
https://github.com/SecureApiGateway/SecureApiGateway/issues/863
> 863: Adding FapiInteractionIdContext which manages storing an x-fapi-interaction-id in a ThreadLocal

- secure-api-gateway-ob-uk-common-obie-datamodel/pom.xml
Removed the following dependencies from the obie-datamodel module:
- springfox-swagger-ui
- nimbus-jose-jwt
- springfox-swagger-ui
- javax.el
Changing hibernate-validator-cdi to a test scope dependency
https://github.com/SecureApiGateway/SecureApiGateway/issues/1238
> 1238: Dependency cleanup

- secure-api-gateway-ob-uk-common-obie-datamodel/pom.xml
springfox is not being used, it is only required as it transitively pulls in the swagger-annotations dependency required by our code.
Removing springfox and adding swagger-annotations.
Adding spring-boot-starter-web dependency as this was also being pulled in transitively by springfox and is needed for the Validated annotations.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1244
> 1244: Remove springfox dependency

- pom.xml
Bump parent version to release version
Version: https://github.com/SecureApiGateway/SecureApiGateway/issues/1251
> 1251: Prepare next SAPIG release of 2.3.0

- .github/workflows/codeql.yml
Enabling CodeQL scanning for this repo.
The default scanning configuration is not working, therefore a custom codeql.yml file needs to be added to the repo.
The codeql.yml contains the default settings for a Java project (provided by GitHub), with a change to add the setup-java action in order to configure the build to use Java 17 (without this Java 11 is being used and is failing).
These changes are currently untested as a commit is needed first, further changes are therefore likely.
https://github.com/SecureApiGateway/SecureApiGateway/issues/900
> 900: Configuring CodeQL

- .github/workflows/codeql.yml
- Removing scan on pull request as it slows down the development process
- Scanning after a merge and on a weekly schedule are sufficient
- Security alerts will be monitored and should be aimed to be fixed prior to making a release
- Adding maven cache support
https://github.com/SecureApiGateway/SecureApiGateway/issues/900
> 900: CodeQL configuration changes

- pom.xml
Using the latest version of the parent pom to pick up the latest dependency updates.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1364
> 1364: Update parent version to 2.3.2-SNAPSHOT

- secure-api-gateway-ob-uk-common-obie-datamodel/pom.xml
- secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/v4/payment/OBWriteDomesticScheduledConsentResponse5Data.java
- secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/v4/payment/OBWriteDomesticStandingOrderConsentResponse6Data.java
Code generation for Domestic Scheduled Payments and Standing Orders has been fixed to use the shared OBPaymentConsentStatus type.
All Consent Response types status field are now using OBPaymentConsentStatus.
> 1440: Fix all consent responses to use OBPaymentConsentStatus type

- secure-api-gateway-ob-uk-common-obie-datamodel/pom.xml
- secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/v4/fund/OBFundsConfirmation1.java
- secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/v4/fund/OBFundsConfirmation1Data.java
- secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/v4/fund/OBFundsConfirmation1DataInstructedAmount.java
- secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/v4/fund/OBFundsConfirmationConsent1.java
- secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/v4/fund/OBFundsConfirmationConsent1Data.java
- secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/v4/fund/OBFundsConfirmationConsent1DataDebtorAccount.java
- secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/v4/fund/OBFundsConfirmationConsentResponse1.java
- secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/v4/fund/OBFundsConfirmationConsentResponse1Data.java
- secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/v4/fund/OBFundsConfirmationConsentStatus.java
- secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/v4/fund/OBFundsConfirmationResponse1.java
- secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/v4/fund/OBFundsConfirmationResponse1Data.java
- secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/v4/fund/OBProxy1.java
- secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/v4/fund/OBStatusReason.java
- secure-api-gateway-ob-uk-common-obie-datamodel/src/main/resources/specification/4.0.0/confirmation-funds-openapi.yaml
Code generated from confirmation-funds-openapi.yaml using OB v4 schema into pkg: uk.org.openbanking.datamodel.v4.fund
Adjusted code gen config to create OBFundsConfirmationConsentStatus as a top-level class rather than having it nested.
> 1440: Add v4 confirmation of funds data model

- secure-api-gateway-ob-uk-common-obie-datamodel/pom.xml
- secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/v4/event/OBEvent1.java
- secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/v4/event/OBEventLink1.java
- secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/v4/event/OBEventNotification1.java
- secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/v4/event/OBEventPolling1.java
- secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/v4/event/OBEventPolling1SetErrsValue.java
- secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/v4/event/OBEventPollingResponse1.java
- secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/v4/event/OBEventResourceUpdate1.java
- secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/v4/event/OBEventSubject1.java
- secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/v4/event/OBEventSubscription1.java
- secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/v4/event/OBEventSubscription1Data.java
- secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/v4/event/OBEventSubscriptionResponse1.java
- secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/v4/event/OBEventSubscriptionResponse1Data.java
- secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/v4/event/OBEventSubscriptionsResponse1.java
- secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/v4/event/OBEventSubscriptionsResponse1Data.java
- secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/v4/event/OBEventSubscriptionsResponse1DataEventSubscriptionInner.java
Code generated from event-openapi.yaml and event-notifications-openapi.yaml using OB v4 schema into pkg: uk.org.openbanking.datamodel.v4.event
> 1440: Add v4 events data model

- secure-api-gateway-ob-uk-common-obie-datamodel/pom.xml
- secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/v4/vrp/OBDomesticVRPConsentResponseData.java
- secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/v4/vrp/OBDomesticVRPConsentStatus.java
- secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/v4/vrp/OBDomesticVRPControlParameters.java
The new status name provides consistency with the status names for other schemas.
> 1440: Rename OBDomesticVRPConsentResponseDataStatus to OBDomesticVRPConsentStatus

- secure-api-gateway-ob-uk-common-obie-datamodel/pom.xml
Configure the code generator to only produce an interface for the API with no default methods.
> 1440: Add code generator options for generating APIs

- secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/common/FRExternalCreditorReferenceTypeCode.java
- secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/common/FRExternalDocumentTypeCode.java
- secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/common/FRPostalAddress.java
- secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/common/FRReferredDocumentInformation.java
- secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/common/FRRemittanceInformationStructured.java
- secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/common/FRRemittanceInformationStructuredCreditorReferenceInformation.java
- secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/ConversionUtils.java
- secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/common/FRPostalAddressConverter.java
- secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/common/FRRemittanceInformationConverter.java
- secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/mapper/FRModelMapper.java
- secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/payment/FRExternalCategoryPurposeCode.java
- secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/payment/FRExternalMandateClassificationCode.java
- secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/payment/FRExternalProxyAccountTypeCode.java
- secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/payment/FRMandateRelatedInformation.java
- secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/payment/FRProxy.java
- secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/payment/FRRegulatoryAuthority.java
- secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/payment/FRRegulatoryReporting.java
- secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/payment/FRRegulatoryReportingDebitCreditReportingIndicator.java
- secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/payment/FRStandingOrderFrequency.java
- secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/payment/FRStandingOrderFrequencyCode.java
- secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/payment/FRStructuredRegulatoryReporting.java
- secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/payment/FRUltimateCreditor.java
- secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/payment/FRUltimateDebtor.java
- secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/payment/FRWriteDomesticStandingOrderDataInitiation.java
- secure-api-gateway-ob-uk-common-datamodel/src/test/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/ConversionUtilsTest.java
- secure-api-gateway-ob-uk-common-datamodel/src/test/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/common/FRPostalAddressConverterTest.java
- secure-api-gateway-ob-uk-common-datamodel/src/test/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/testsupport/FRPostalAddressTestDataFactory.java
FRWriteDomesticStandingOrderDataInitiation has been updated to include the new fields added in v4.
Several top level v3 fields move into new subtype FRMandateRelatedInformation. The fields are duplicated to allow v3 and v4 data to be decoded from the database into the same object.
FRPostalAddress has been updated to include the new fields added in OBPostalAddress7. 
The addressType field has changed from an enum to a String, this allows us to support the new 4-letter code address types.
The FRPostalAddressConverter has been updated to support converting v3 addressType values to v4 and vice versa, this means that existing addresses stored in the database can be translated to v3 or v4 as required.
This has been updated to change unstructured field from String to List<String>. Spring Data …
> 1440: Add OB v4 Domestic Standing Orders support to the FR data model
