SecureApiGateway/secure-api-gateway-ob-uk-common

securebanking-openbanking-uk-forgerock-datamodel/src/main/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/account/FRBankAccount.java, securebanking-openbanking-uk-forgerock-datamodel/src/main/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/account/FRBankAccountWithBalance.java
Added FRBankAccount and FRBankAccountWithBalance for retrieving a user's bank
Issue: https://github.com/SecureBankingAcceleratorToolkit/SecureBankingAcceleratorToolkit/issues/43
=> 43 - FRBankAccount and FRBankAccountWithBalance

securebanking-openbanking-uk-obie-datamodel/src/test/java/uk/org/openbanking/testsupport/payment/OBWriteDomesticConsentTestDataFactory.java, securebanking-openbanking-uk-obie-datamodel/src/test/java/uk/org/openbanking/testsupport/payment/OBWriteDomesticScheduledConsentTestDataFactory.java, securebanking-openbanking-uk-obie-datamodel/src/test/java/uk/org/openbanking/testsupport/payment/OBWriteDomesticStandingOrderConsentTestDataFactory.java, securebanking-openbanking-uk-obie-datamodel/src/test/java/uk/org/openbanking/testsupport/payment/OBWriteInternationalConsentTestDataFactory.java, securebanking-openbanking-uk-obie-datamodel/src/test/java/uk/org/openbanking/testsupport/payment/OBWriteInternationalStandingOrderConsentTestDataFactory.java
Test data factories for creating various payments.
Issue: https://github.com/SecureBankingAcceleratorToolkit/SecureBankingAcceleratorToolkit/issues/45
=> 45 Test data factories for creating payments

securebanking-openbanking-uk-forgerock-datamodel/src/main/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/payment/FRDomesticDataInitiation.java, securebanking-openbanking-uk-forgerock-datamodel/src/main/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/payment/FRInternationalDataInitiation.java, securebanking-openbanking-uk-forgerock-datamodel/src/main/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/payment/FRWriteDomesticDataInitiation.java, securebanking-openbanking-uk-forgerock-datamodel/src/main/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/payment/FRWriteDomesticScheduledDataInitiation.java, securebanking-openbanking-uk-forgerock-datamodel/src/main/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/payment/FRWriteDomesticStandingOrderDataInitiation.java, securebanking-openbanking-uk-forgerock-datamodel/src/main/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/payment/FRWriteInternationalDataInitiation.java, securebanking-openbanking-uk-forgerock-datamodel/src/main/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/payment/FRWriteInternationalScheduledDataInitiation.java, securebanking-openbanking-uk-forgerock-datamodel/src/main/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/payment/FRWriteInternationalStandingOrderDataInitiation.java, securebanking-openbanking-uk-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/payment/OBWriteInternationalResponse4Data.java
- Added regenerated OBWriteInternationalResponse4Data with refund field
- Added DataInitiation interfaces to provide common functionality across variants
**Issue**: https://github.com/SecureBankingAcceleratorToolkit/SecureBankingAcceleratorToolkit/issues/45
=> 45 Additional refund changes

securebanking-openbanking-uk-common/pom.xml, securebanking-openbanking-uk-common/src/main/java/com/forgerock/securebanking/openbanking/uk/common/api/meta/IntentType.java, securebanking-openbanking-uk-common/src/main/java/com/forgerock/securebanking/openbanking/uk/common/api/meta/OBConstants.java, securebanking-openbanking-uk-common/src/main/java/com/forgerock/securebanking/openbanking/uk/common/claim/Claim.java, securebanking-openbanking-uk-common/src/main/java/com/forgerock/securebanking/openbanking/uk/common/claim/Claims.java, securebanking-openbanking-uk-common/src/main/java/com/forgerock/securebanking/openbanking/uk/common/claim/JwsClaimsUtils.java, securebanking-openbanking-uk-error/src/main/java/com/forgerock/securebanking/openbanking/uk/error/ErrorCode.java, securebanking-openbanking-uk-error/src/main/java/com/forgerock/securebanking/openbanking/uk/error/OBRIErrorType.java, securebanking-openbanking-uk-forgerock-datamodel/pom.xml, securebanking-openbanking-uk-forgerock-datamodel/src/main/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/account/FRAccount.java, securebanking-openbanking-uk-forgerock-datamodel/src/main/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/account/FRAccountAccessConsent.java, securebanking-openbanking-uk-forgerock-datamodel/src/main/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/account/FRAccountConsent.java, securebanking-openbanking-uk-forgerock-datamodel/src/main/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/payment/FRConsentStatusCode.java, securebanking-openbanking-uk-forgerock-datamodel/src/main/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/payment/FRDomesticPaymentConsent.java, securebanking-openbanking-uk-forgerock-datamodel/src/main/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/payment/FRInternationalPaymentConsent.java, securebanking-openbanking-uk-forgerock-datamodel/src/main/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/payment/FRPaymentConsent.java, securebanking-openbanking-uk-forgerock-datamodel/src/main/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/tpp/Tpp.java, securebanking-openbanking-uk-forgerock-datamodel/src/test/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/testsupport/FRAccountIdentifierTestDataFactory.java, securebanking-openbanking-uk-forgerock-datamodel/src/test/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/testsupport/account/FRAccountAccessConsentTestDataFactory.java, securebanking-openbanking-uk-forgerock-datamodel/src/test/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/testsupport/account/FRAccountTestDataFactory.java, securebanking-openbanking-uk-forgerock-datamodel/src/test/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/testsupport/account/FRBankAccountWithBalanceTestDataFactory.java, securebanking-openbanking-uk-forgerock-datamodel/src/test/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/testsupport/account/FRFinancialAccountTestDataFactory.java, securebanking-openbanking-uk-forgerock-datamodel/src/test/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/testsupport/payment/FRDomesticPaymentConsentTestDataFactory.java, securebanking-openbanking-uk-forgerock-datamodel/src/test/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/testsupport/payment/FRPaymentRiskTestDataFactory.java, securebanking-openbanking-uk-forgerock-datamodel/src/test/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/testsupport/payment/FRRemittanceInformationTestDataFactory.java, securebanking-openbanking-uk-forgerock-datamodel/src/test/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/testsupport/payment/FRWriteDomesticDataInitiationTestDataFactory.java, securebanking-openbanking-uk-forgerock-datamodel/src/test/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/testsupport/tpp/TppTestDataFactory.java
- Added JWT claims related code
- Added consent related interfaces and initial classes
- Introduced initial Tpp model class.
**Issue**: https://github.com/SecureBankingAcceleratorToolkit/SecureBankingAcceleratorToolkit/issues/58
=> 58 Initial RCS consent related requirements

securebanking-openbanking-uk-forgerock-datamodel/src/main/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/payment/FRDomesticDataInitiation.java, securebanking-openbanking-uk-forgerock-datamodel/src/main/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/payment/FRDomesticPaymentConsent.java, securebanking-openbanking-uk-forgerock-datamodel/src/main/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/payment/FRInternationalDataInitiation.java, securebanking-openbanking-uk-forgerock-datamodel/src/main/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/payment/FRInternationalPaymentConsent.java, securebanking-openbanking-uk-forgerock-datamodel/src/main/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/payment/FRPaymentConsent.java
Fixes for Jackson serialisation/deserialisation
Issue: https://github.com/SecureBankingAcceleratorToolkit/SecureBankingAcceleratorToolkit/issues/58
=> 58 Fixes for Jackson serialisation/deserialisation

securebanking-openbanking-uk-forgerock-datamodel/src/main/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/payment/FRDomesticPaymentConsent.java, securebanking-openbanking-uk-forgerock-datamodel/src/main/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/payment/FRInternationalPaymentConsent.java, securebanking-openbanking-uk-forgerock-datamodel/src/main/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/payment/FRPaymentConsent.java, securebanking-openbanking-uk-forgerock-datamodel/src/test/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/testsupport/payment/FRDomesticPaymentConsentTestDataFactory.java
Issue: https://github.com/SecureBankingAcceleratorToolkit/SecureBankingAcceleratorToolkit/issues/58
=> 58 Remove Tpp from the consent objects

securebanking-openbanking-uk-forgerock-datamodel/src/main/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/payment/FRPaymentRisk.java, securebanking-openbanking-uk-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/payment/OBRisk1DeliveryAddress.java, securebanking-openbanking-uk-obie-datamodel/src/test/java/uk/org/openbanking/jackson/payment/OBRiskTest.java, securebanking-openbanking-uk-obie-datamodel/src/test/java/uk/org/openbanking/testsupport/payment/OBRisk1TestDataFactory.java
Changed `countrySubDivision` from `List<String>` to `String`
**Issue**: https://github.com/OpenBankingToolkit/openbanking-toolkit/issues/27
=> 27 - Change countrySubDivision from List to String

securebanking-openbanking-uk-forgerock-datamodel/src/main/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/converter/payment/FRExchangeRateConverter.java, securebanking-openbanking-uk-obie-datamodel/src/test/java/uk/org/openbanking/testsupport/payment/OBExchangeRateTestDataFactory.java
Additional ExchangeRateInformation type
**Issue**: https://github.com/OpenBankingToolkit/openbanking-toolkit/issues/27
=> 27 - Additional ExchangeRateInformation type

.github/workflows/pr.yml, .gitignore, README.md, legal/LICENSE-2.0-HEADER.txt, legal/LICENSE-2.0.txt, pom.xml, securebanking-openbanking-uk-bom/README.md, securebanking-openbanking-uk-bom/pom.xml, securebanking-openbanking-uk-common/pom.xml, securebanking-openbanking-uk-error/pom.xml, securebanking-openbanking-uk-forgerock-datamodel/pom.xml, securebanking-openbanking-uk-obie-datamodel/pom.xml
- legal Improvements
- Defined and Added `.uk` to maven group to differentiate `secure banking base/common` artifacts from `secure banking: specific implementation` artifacts like as uk spec.
- Fixed some maven plugin versions
=> improve the project structure and maven files

pom.xml, securebanking-openbanking-uk-bom/pom.xml, securebanking-openbanking-uk-common/pom.xml, securebanking-openbanking-uk-error/pom.xml, securebanking-openbanking-uk-forgerock-datamodel/pom.xml, securebanking-openbanking-uk-obie-datamodel/pom.xml
- Upgrade parent to 1.0.2
- Upgrade version to 1.0.2
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/90
=> 90: account access and domestic payment journeys

pom.xml, securebanking-openbanking-uk-bom/pom.xml, securebanking-openbanking-uk-common/pom.xml, securebanking-openbanking-uk-error/pom.xml, securebanking-openbanking-uk-forgerock-datamodel/pom.xml, securebanking-openbanking-uk-obie-datamodel/pom.xml
- Bumped starter parent 1.0.3-SNAPSHOT
- Upgraded version to 1.0.3-SNAPSHOT
=> Upgrade starter parent and version

.gitignore, securebanking-openbanking-uk-forgerock-datamodel/src/main/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/common/FRAccountIdentifier.java, securebanking-openbanking-uk-forgerock-datamodel/src/main/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/common/FRAmount.java, securebanking-openbanking-uk-forgerock-datamodel/src/main/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/common/FRPostalAddress.java, securebanking-openbanking-uk-forgerock-datamodel/src/main/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/common/FRRemittanceInformation.java, securebanking-openbanking-uk-forgerock-datamodel/src/main/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/common/FRSupplementaryData.java, securebanking-openbanking-uk-forgerock-datamodel/src/main/java/com/forgerock/securebanking/common/openbanking/uk/forgerock/datamodel/payment/FRWriteDomesticDataInitiation.java
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/233
=> Roll back "Add json properties #231"

securebanking-openbanking-uk-common/src/main/java/com/forgerock/securebanking/openbanking/uk/common/api/meta/OBVersion.java
Added missing versions 3.1.7 and 3.1.8
=> Updating versions list

securebanking-openbanking-uk-common/pom.xml, securebanking-openbanking-uk-common/src/main/java/com/forgerock/securebanking/openbanking/uk/common/api/meta/forgerock/FRFrequency.java, securebanking-openbanking-uk-common/src/main/java/com/forgerock/securebanking/openbanking/uk/common/api/meta/forgerock/FRFrequencyType.java, securebanking-openbanking-uk-common/src/main/java/com/forgerock/securebanking/openbanking/uk/common/api/meta/forgerock/FRQuarterType.java, securebanking-openbanking-uk-common/src/main/java/com/forgerock/securebanking/openbanking/uk/common/api/meta/obie/OBConstants.java, securebanking-openbanking-uk-common/src/main/java/com/forgerock/securebanking/openbanking/uk/common/api/meta/obie/OBGroupName.java, securebanking-openbanking-uk-common/src/main/java/com/forgerock/securebanking/openbanking/uk/common/api/meta/obie/OBHeaders.java, securebanking-openbanking-uk-common/src/main/java/com/forgerock/securebanking/openbanking/uk/common/api/meta/obie/OBJoseHeaderClaims.java, securebanking-openbanking-uk-common/src/main/java/com/forgerock/securebanking/openbanking/uk/common/api/meta/obie/OBVersion.java, securebanking-openbanking-uk-common/src/main/java/com/forgerock/securebanking/openbanking/uk/common/api/meta/share/IntentType.java, securebanking-openbanking-uk-common/src/main/java/com/forgerock/securebanking/openbanking/uk/common/claim/JwsClaimsUtils.java, securebanking-openbanking-uk-error/src/main/java/com/forgerock/securebanking/openbanking/uk/error/OBRIErrorType.java, securebanking-openbanking-uk-obie-datamodel/pom.xml, securebanking-openbanking-uk-obie-datamodel/src/test/java/uk/org/openbanking/testsupport/payment/OBWriteDomesticStandingOrderConsentTestDataFactory.java, securebanking-openbanking-uk-obie-datamodel/src/test/java/uk/org/openbanking/testsupport/payment/OBWriteInternationalStandingOrderConsentTestDataFactory.java
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/341
=> 341: Move the FRFrequency classes in securebanking-openbanking-uk-common

securebanking-openbanking-uk-common/src/main/java/com/forgerock/securebanking/openbanking/uk/common/api/meta/forgerock/FRFrequency.java
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/341
=> 341: Fix the FRFrequency constructor

securebanking-openbanking-uk-obie-datamodel/src/test/java/uk/org/openbanking/testsupport/payment/OBExchangeRateTestDataFactory.java
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/444
=> 444: The Currency Of Transfer is different from the Exchange Unit Currency

pom.xml, securebanking-openbanking-uk-bom/pom.xml, securebanking-openbanking-uk-common/pom.xml, securebanking-openbanking-uk-error/pom.xml, securebanking-openbanking-uk-forgerock-datamodel/pom.xml, securebanking-openbanking-uk-obie-datamodel/pom.xml, securebanking-openbanking-uk-obie-datamodel/src/test/java/uk/org/openbanking/testsupport/payment/OBWriteFileConsentTestDataFactory.java
- Added test support factory for file payments
- Updated securebanking-parent to 1.0.6-SNAPSHOT
- Updated developer version to 1.1.8-SNAPSHOT
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/590
=> 590: file payment backoffice validations

.github/workflows/merge-master.yml
- Deleted skip test on deploy to build the test jars
Issue: https://github.com/secureapigateway/secureapigateway/issues/835
=> 835: rename repository merge master fixes

.github/workflows/merge-master.yml, .github/workflows/release.yml, pom.xml, secure-api-gateway-ob-uk-common-bom/pom.xml
Changes to make ready to build a release artifact
- Bumped parent release candidate
- Updated merge master workflow
- Updated pom file scm section
- Added release caller workflow
Issue: https://github.com/secureapigateway/secureapigateway/issues/812
=> 812: release action

secure-api-gateway-ob-uk-common-error/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/error/OBRIErrorType.java, secure-api-gateway-ob-uk-common-obie-datamodel/src/test/java/uk/org/openbanking/testsupport/payment/OBWriteDomesticScheduledConsentTestDataFactory.java, secure-api-gateway-ob-uk-common-obie-datamodel/src/test/java/uk/org/openbanking/testsupport/payment/OBWriteDomesticStandingOrderConsentTestDataFactory.java, secure-api-gateway-ob-uk-common-obie-datamodel/src/test/java/uk/org/openbanking/testsupport/payment/OBWriteFileConsentTestDataFactory.java, secure-api-gateway-ob-uk-common-obie-datamodel/src/test/java/uk/org/openbanking/testsupport/payment/OBWriteInternationalScheduledConsentTestDataFactory.java, secure-api-gateway-ob-uk-common-obie-datamodel/src/test/java/uk/org/openbanking/testsupport/payment/OBWriteInternationalStandingOrderConsentTestDataFactory.java
- Updated OBErrorType to add error reason for validations
- Updated Test data factories to support new test cases
Issue: https://github.com/secureapigateway/secureapigateway/issues/947
=> 947: payment validations data test support

secure-api-gateway-ob-uk-common-error/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/error/ErrorCode.java
https://github.com/SecureApiGateway/SecureApiGateway/issues/1012
=> 1012: Adding ErrorCode: OBRI.Consent.Not.Found

secure-api-gateway-ob-uk-common-error/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/error/OBRIErrorType.java
https://github.com/SecureApiGateway/SecureApiGateway/issues/1035
=> 1035: Cleanup error message for PERMISSIONS_INVALID

secure-api-gateway-ob-uk-common-error/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/error/OBRIErrorType.java
https://github.com/SecureApiGateway/SecureApiGateway/issues/1054
=> 1054: Fixing error when VRP creditor account does not match consent

secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/payment/FRWriteDomesticScheduledConsentConverter.java, secure-api-gateway-ob-uk-common-datamodel/src/test/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/payment/FRWriteDomesticScheduledConsentConverterTest.java
https://github.com/SecureApiGateway/SecureApiGateway/issues/1060
=> 1060: Adding converter to transform FR data-model to OB data-model for Domestic Scheduled Payment Consents

secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/common/FRChargeConverter.java, secure-api-gateway-ob-uk-common-datamodel/src/test/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/common/FRChargeConverterTest.java
https://github.com/SecureApiGateway/SecureApiGateway/issues/1060
=> 1060: Adding FRChargeConverter helper methods which work with lists of charges

secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/payment/FRWriteDomesticStandingOrderConsentConverter.java, secure-api-gateway-ob-uk-common-datamodel/src/test/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/payment/FRWriteDomesticStandingOrderConsentConverterTest.java
https://github.com/SecureApiGateway/SecureApiGateway/issues/1061
=> 1061: Adding method to convert Domestic Standing Order Consents from FR data-model back to OB model

secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/payment/FRWriteFileConsentConverter.java, secure-api-gateway-ob-uk-common-datamodel/src/test/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/payment/FRWriteFileConsentConverterTest.java
https://github.com/SecureApiGateway/SecureApiGateway/issues/1065
=> 1065: Adding method to convert File Payment Consents from FR data-model back to OB model

secure-api-gateway-ob-uk-common-error/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/error/ErrorCode.java, secure-api-gateway-ob-uk-common-error/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/error/OBRIErrorType.java
https://github.com/SecureApiGateway/SecureApiGateway/issues/1065
=> 1065: Adding ErrorCode when trying to retrieve a File for a File Payment Consent when no file has been uploaded yet

secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/customerinfo/FRAddressTypeCode.java, secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/customerinfo/FRCustomerInfo.java, secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/customerinfo/FRCustomerInfoAddress.java, secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/customerinfo/AddressTypeCode.java, secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/customerinfo/CustomerInfo.java, secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/customerinfo/CustomerInfoAddress.java, secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/customerinfo/ReadCustomerInfo.java, secure-api-gateway-ob-uk-common-shared/src/main/java/com/forgerock/sapi/gateway/uk/common/shared/api/meta/obie/OBGroupName.java, secure-api-gateway-ob-uk-common-shared/src/main/java/com/forgerock/sapi/gateway/uk/common/shared/api/meta/share/IntentType.java
- Added OB objects to support user account customer info resource
- Added FR dto objects to build user account customer info responses thru components
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1069
=> 1069: Customer info support

secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/payment/FRWriteInternationalScheduledConsentConverter.java, secure-api-gateway-ob-uk-common-datamodel/src/test/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/payment/FRWriteInternationalScheduledConsentConverterTest.java
https://github.com/SecureApiGateway/SecureApiGateway/issues/1063
=> 1063: Adding converter to transform FRWriteInternationalScheduledConsent back to the OB data-model

secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/payment/FRWriteInternationalStandingOrderConsentConverter.java, secure-api-gateway-ob-uk-common-datamodel/src/test/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/payment/FRWriteInternationalStandingOrderConsentConverterTest.java
https://github.com/SecureApiGateway/SecureApiGateway/issues/1064
=> 1064: Adding converter to transform FRWriteInternationalStandingOrderConsent back to the OB data-model

secure-api-gateway-ob-uk-common-error/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/error/OBRIErrorType.java
- Added new error types for funds confirmation availability
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1093
=> 1093: Funds confirmation error types added

pom.xml, secure-api-gateway-ob-uk-common-bom/pom.xml, secure-api-gateway-ob-uk-common-datamodel/pom.xml, secure-api-gateway-ob-uk-common-error/pom.xml, secure-api-gateway-ob-uk-common-obie-datamodel/pom.xml, secure-api-gateway-ob-uk-common-shared/pom.xml
- Upgrade version to 2.0.0
- Bumped parent version 2.0.0
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1099
=> 1099: upgrade version to 2.0.0

pom.xml, secure-api-gateway-ob-uk-common-bom/pom.xml, secure-api-gateway-ob-uk-common-datamodel/pom.xml, secure-api-gateway-ob-uk-common-error/pom.xml, secure-api-gateway-ob-uk-common-obie-datamodel/pom.xml, secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/discovery/OBDiscoveryAPILinks.java, secure-api-gateway-ob-uk-common-shared/pom.xml
- fix to display aggregated polling API in the discovery endpoint
- Updated development version to 2.0.3-SNAPSHOT
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1125
=> 1125: aggregated polling discovery fix

secure-api-gateway-ob-uk-common-shared/src/main/java/com/forgerock/sapi/gateway/uk/common/shared/api/meta/forgerock/FRFrequency.java, secure-api-gateway-ob-uk-common-shared/src/main/java/com/forgerock/sapi/gateway/uk/common/shared/api/meta/forgerock/FRFrequencyType.java, secure-api-gateway-ob-uk-common-shared/src/test/java/com/forgerock/sapi/gateway/uk/common/shared/api/meta/forgerock/FRFrequencyTest.java
- Upgrage FRFrequency class to format the frequency as readable value to be displayed in the UI
- Added unit test for FRFrequency
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1026
=> 1026: frequency readable value to display it in the UI

secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/event/FREventMessage.java, secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/event/FREventMessages.java
- Moved FREventsMessages and FREventsMessage to import events from RS to common library
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1130
=> 1130: moved FREventsMessages and FREventsMessage to common

pom.xml, secure-api-gateway-ob-uk-common-bom/pom.xml, secure-api-gateway-ob-uk-common-datamodel/pom.xml, secure-api-gateway-ob-uk-common-error/pom.xml, secure-api-gateway-ob-uk-common-obie-datamodel/pom.xml, secure-api-gateway-ob-uk-common-shared/pom.xml
- Updated development version to 2.1.0-SNAPSHOT
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1148
=> 1148: prepare release 2.1.0

pom.xml, secure-api-gateway-ob-uk-common-bom/pom.xml, secure-api-gateway-ob-uk-common-datamodel/pom.xml, secure-api-gateway-ob-uk-common-error/pom.xml, secure-api-gateway-ob-uk-common-obie-datamodel/pom.xml, secure-api-gateway-ob-uk-common-shared/pom.xml
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1182
=> Prepare eminem release 2.2.0

pom.xml
See PR: https://github.com/SecureApiGateway/secure-api-gateway-parent/pull/81
https://github.com/SecureApiGateway/SecureApiGateway/issues/1223
=> 1223: Updating to latest parent version which updates guava dependency version

pom.xml
https://github.com/SecureApiGateway/SecureApiGateway/issues/1139
=> 1139: Updating Java version to 17

secure-api-gateway-ob-uk-common-obie-datamodel/pom.xml
https://github.com/SecureApiGateway/SecureApiGateway/issues/1243
=> 1243: Cleanup code-gen config + add documentation

secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/vrp/OBDomesticVRPConsentResponse.java, secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/vrp/OBDomesticVRPResponse.java
Reusing the common Meta definition for VRPs
https://github.com/SecureApiGateway/SecureApiGateway/issues/1243
=> 1243: Re-gen VRP data model

.github/workflows/merge-master.yml, .github/workflows/pr.yml
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1257
=> 1257: Update java action and distribution

.github/workflows/merge-master.yml, .github/workflows/pr.yml
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1264
=> 1264: Update actions that have deprecations

secure-api-gateway-ob-uk-common-obie-datamodel/README.md
https://github.com/SecureApiGateway/SecureApiGateway/issues/1243
=> 1243: Improve README for code gen

secure-api-gateway-ob-uk-common-shared/src/main/java/com/forgerock/sapi/gateway/uk/common/shared/api/meta/obie/OBVersion.java
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1311
Description: Added v3_1_11 to OBVersion enum.
=> 1311: Adding v3_1_11 to OBVersion enum

pom.xml
Bump parent dependency to release 3.0.0
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1404
=> 1404: Create and Release SAPIG Core and OB

.github/workflows/codeql.yml, .github/workflows/merge.yml, .github/workflows/pr.yml
Enable manual trigger for PR and Merge workflows
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1465
=> 1465: Allow Manual run of workflows

secure-api-gateway-ob-uk-common-shared/src/main/java/com/forgerock/sapi/gateway/uk/common/shared/api/meta/obie/OBVersion.java, secure-api-gateway-ob-uk-common-shared/src/test/java/com/forgerock/sapi/gateway/uk/common/shared/api/meta/obie/OBVersionTest.java
=> 1440: Add v4.0.0 to OBVersion enum

.github/workflows/pr.yml
Need to pass in dockerTag for snapshot version
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1543
=> 1543: Upload artifacts on PR build

secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/common/FRFinancialAgent.java, secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/common/FRReferredDocumentInformation.java, secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/v3/common/FRRemittanceInformationConverter.java, secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/v4/common/FRAccountIdentifierConverter.java, secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/v4/common/FRConsentStatusConverter.java, secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/v4/common/FRPaymentDetailsStatusConverter.java, secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/v4/payment/FRDataSCASupportDataConverter.java, secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/v4/payment/FRWriteDomesticConsentConverter.java, secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/v4/payment/FRWriteDomesticConverter.java, secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/payment/FRWriteDomesticDataInitiation.java, secure-api-gateway-ob-uk-common-datamodel/src/test/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/v4/payment/FRWriteDomesticConsentConverterTest.java, secure-api-gateway-ob-uk-common-obie-datamodel/pom.xml, secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/v4/payment/OBWriteDomesticConsentResponse5Data.java, secure-api-gateway-ob-uk-common-obie-datamodel/src/test/java/uk/org/openbanking/testsupport/v4/payment/OBRemittanceInformationTestDataFactory.java, secure-api-gateway-ob-uk-common-obie-datamodel/src/test/java/uk/org/openbanking/testsupport/v4/payment/OBWriteDomesticConsentTestDataFactory.java
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1555
Adding datamodel support for domestic payments v4.0.0
=> Domestic Payments

secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/v4/event/FREventPollingConverter.java, secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/v4/event/FREventSubscriptionConverter.java
- adding converters for event notification flow v4.
=> LOB-196-event-notifications-flows-v4

secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/v3/common/FRRemittanceInformationConverter.java, secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/v3/common/FRSupplementaryDataConverter.java, secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/v4/common/FRAccountIdentifierConverter.java, secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/v4/common/FRConsentStatusConverter.java, secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/v4/common/FRPaymentDetailsStatusConverter.java, secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/v4/common/FRSubmissionStatusConverter.java, secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/v4/payment/FRRegulatoryReportingConverter.java, secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/v4/vrp/FRDomesticVRPConsentConverters.java, secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/v4/vrp/FRDomesticVrpConverters.java, secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/v4/vrp/FRVrpInteractionTypesConverter.java, secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/vrp/FRDomesticVrpInstruction.java, secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/vrp/FRWriteDomesticVrpDataInitiation.java, secure-api-gateway-ob-uk-common-error/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/error/ErrorCode.java, secure-api-gateway-ob-uk-common-error/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/error/OBRIErrorType.java, secure-api-gateway-ob-uk-common-obie-datamodel/pom.xml, secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/v4/vrp/OBDomesticVRPConsentRequestData.java, secure-api-gateway-ob-uk-common-obie-datamodel/src/test/java/uk/org/openbanking/testsupport/v4/vrp/OBDomesticVRPConsentResponseTestDataFactory.java, secure-api-gateway-ob-uk-common-obie-datamodel/src/test/java/uk/org/openbanking/testsupport/v4/vrp/OBDomesticVrpCommonTestDataFactory.java, secure-api-gateway-ob-uk-common-obie-datamodel/src/test/java/uk/org/openbanking/testsupport/v4/vrp/OBDomesticVrpConsentRequestTestDataFactory.java, secure-api-gateway-ob-uk-common-obie-datamodel/src/test/java/uk/org/openbanking/testsupport/v4/vrp/OBDomesticVrpRequestTestDataFactory.java, secure-api-gateway-ob-uk-common-obie-datamodel/src/test/java/uk/org/openbanking/testsupport/v4/vrp/OBVrpFundsConfirmationRequestTestDataFactory.java
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1573
Added support for domestic vrp's.
=> Domestic VRP support

secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/v4/common/FRAccountIdentifierConverter.java, secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/v4/common/FRFundsConfirmationConsentStatusConverter.java, secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/v4/funds/FRFundsConfirmationConsentConverter.java, secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/v4/funds/FRFundsConfirmationConverter.java, secure-api-gateway-ob-uk-common-datamodel/src/test/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/v4/funds/FRFundsConfirmationConsentConverterTest.java, secure-api-gateway-ob-uk-common-obie-datamodel/pom.xml, secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/v4/fund/OBFundsConfirmationConsent1Data.java, secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/v4/fund/OBFundsConfirmationConsent1DataDebtorAccount.java, secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/v4/fund/OBFundsConfirmationConsentResponse1Data.java
LOB-194-funds-confirmation-v4
- adding datamodel support, converters for funds confirmation flow v4.0.0.
=> Funds Confirmation

secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/v4/payment/FRFrequency6Converter.java, secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/v4/payment/FRMandateRelatedInformationConverter.java, secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/payment/FRMandateRelatedInformation.java, secure-api-gateway-ob-uk-common-shared/src/main/java/com/forgerock/sapi/gateway/uk/common/shared/api/meta/forgerock/FRFrequency.java, secure-api-gateway-ob-uk-common-shared/src/main/java/com/forgerock/sapi/gateway/uk/common/shared/api/meta/forgerock/FRFrequencyCode6.java, secure-api-gateway-ob-uk-common-shared/src/main/java/com/forgerock/sapi/gateway/uk/common/shared/api/meta/forgerock/FRFrequencyType.java, secure-api-gateway-ob-uk-common-shared/src/test/java/com/forgerock/sapi/gateway/uk/common/shared/api/meta/forgerock/FRFrequencyTest.java
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1598
Added v4 frequency types
=> Added frequency types for V4

pom.xml, secure-api-gateway-ob-uk-common-bom/pom.xml, secure-api-gateway-ob-uk-common-datamodel/pom.xml, secure-api-gateway-ob-uk-common-error/pom.xml, secure-api-gateway-ob-uk-common-obie-datamodel/pom.xml, secure-api-gateway-ob-uk-common-shared/pom.xml
Manually add in the version to get the release done
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1602
=> 1602: Build and Deploy SAPIG 4.0.0

pom.xml, secure-api-gateway-ob-uk-common-bom/pom.xml, secure-api-gateway-ob-uk-common-datamodel/pom.xml, secure-api-gateway-ob-uk-common-error/pom.xml, secure-api-gateway-ob-uk-common-obie-datamodel/pom.xml, secure-api-gateway-ob-uk-common-shared/pom.xml
Add revision back into pom.xml files
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1604
=> 1604: Revert Hardcoded Pom.xml for Common and RCS

secure-api-gateway-ob-uk-common-shared/src/main/java/com/forgerock/sapi/gateway/uk/common/shared/api/meta/forgerock/FRFrequency.java
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1598
Fixed v4 frequency types.
=> Update frequency mechanism for v4

secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/v4/account/FRAccountSubTypeConverter.java, secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/v4/account/FRBalanceTypeConverter.java, secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/v4/account/FRCashBalanceConverter.java, secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/v4/account/FRDirectDebitConverter.java, secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/v4/account/FREntryStatusConverter.java, secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/v4/account/FRExternalMandateStatusConverter.java, secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/v4/account/FRFinancialAccountConverter.java, secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/v4/account/FRTransactionConverter.java, secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/v4/payment/FRStandingOrderConverter.java
Added support for new user test data for accounts flow v4
=> LOB-updated-test-data

secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/v4/common/FRAccountIdentifierConverter.java, secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/v4/common/FRConsentStatusConverter.java, secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/v4/common/FRInternationalConsentStatusConverter.java, secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/v4/common/FRPaymentDetailsStatusConverter.java, secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/v4/common/FRSubmissionStatusConverter.java, secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/v4/vrp/FRDomesticVrpConverters.java
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1614
Description:
- fixed 500 server errors
- fixed converters
=> 1614: Fixing OB v4 issues

pom.xml
Use version 4.0.0 for parent 
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1625
=> 1625: SAPIG Release 4.0.2 - Further OB V4 Support

pom.xml, secure-api-gateway-ob-uk-common-bom/pom.xml, secure-api-gateway-ob-uk-common-datamodel/pom.xml, secure-api-gateway-ob-uk-common-error/pom.xml, secure-api-gateway-ob-uk-common-obie-datamodel/pom.xml, secure-api-gateway-ob-uk-common-shared/pom.xml
Revert to revision
Bump revision to 4.0.4-SNAPSHOT
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1626
=> 1626: Prepare repos for Post 4.0.3

secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/v4/vrp/OBDomesticVRPControlParameters.java, secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/v4/vrp/OBDomesticVRPInstruction.java
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1629
=> 1629: Changing supplementaryData object data type

secure-api-gateway-ob-uk-common-datamodel/src/main/java/com/forgerock/sapi/gateway/ob/uk/common/datamodel/converter/v4/common/FRSubmissionStatusConverter.java, secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/v4/account/OBParty2.java, secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/v4/account/OBStatement2StatementFeeInner.java, secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/v4/account/OBStatement2StatementInterestInner.java, secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/v4/fund/OBFundsConfirmationConsent1Data.java, secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/v4/fund/OBFundsConfirmationConsent1DataDebtorAccount.java, secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/v4/fund/OBFundsConfirmationConsentResponse1Data.java, secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/v4/payment/OBWriteDomesticResponse5DataStatus.java, secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/v4/payment/OBWriteFile2DataInitiation.java, secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/v4/payment/OBWriteFileResponse3Data.java, secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/v4/payment/OBWriteFileResponse3DataMultiAuthorisation.java, secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/v4/payment/OBWriteFileResponse3DataMultiAuthorisationStatus.java, secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/v4/payment/OBWriteInternationalResponse5Data.java, secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/v4/payment/OBWriteInternationalResponse5DataStatus.java, secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/v4/payment/OBWriteInternationalScheduledConsent5Data.java, secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/v4/payment/OBWriteInternationalScheduledConsentResponse6Data.java, secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/datamodel/v4/vrp/OBDomesticVRPConsentRequestData.java, secure-api-gateway-ob-uk-common-obie-datamodel/src/main/resources/specification/4.0.0/account-info-openapi-4r3.yaml, secure-api-gateway-ob-uk-common-obie-datamodel/src/main/resources/specification/4.0.0/confirmation-funds-openapi-4r3.yaml, secure-api-gateway-ob-uk-common-obie-datamodel/src/main/resources/specification/4.0.0/event-notifications-openapi-4r3.yaml, secure-api-gateway-ob-uk-common-obie-datamodel/src/main/resources/specification/4.0.0/events-openapi-4r3.yaml, secure-api-gateway-ob-uk-common-obie-datamodel/src/main/resources/specification/4.0.0/payment-initiation-openapi-4r3.yaml, secure-api-gateway-ob-uk-common-obie-datamodel/src/main/resources/specification/4.0.0/vrp-openapi-4r3.yaml
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1634
Description: 
- Generated v4r3 `accounts` data model
- Generated v4r3 `payments` data model
Notes:
1. All the `OBIE` data models were re-generated using `Read/Write API` spec v4r3.
2. `Confirmation funds`, `events`, `vrp` APIs have not been changed.
=> 1634: Re-generating v4.0 release 3 OB data model

pom.xml, secure-api-gateway-ob-uk-common-bom/pom.xml, secure-api-gateway-ob-uk-common-datamodel/pom.xml, secure-api-gateway-ob-uk-common-error/pom.xml, secure-api-gateway-ob-uk-common-obie-datamodel/pom.xml, secure-api-gateway-ob-uk-common-shared/pom.xml
Revert parent to 4.0.0 and remove revision for release
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1642
=> 1642: Create SAPIG 4.0.4

pom.xml
Bump parent version to 5.0.0
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1703
=> 1703: Create SAPIG 5.0.0
